Document: hiredis-okvm
Title: Debian hiredis-okvm Manual
Author: <insert document author here>
Abstract: This manual describes what hiredis-okvm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hiredis-okvm/hiredis-okvm.sgml.gz

Format: postscript
Files: /usr/share/doc/hiredis-okvm/hiredis-okvm.ps.gz

Format: text
Files: /usr/share/doc/hiredis-okvm/hiredis-okvm.text.gz

Format: HTML
Index: /usr/share/doc/hiredis-okvm/html/index.html
Files: /usr/share/doc/hiredis-okvm/html/*.html
